clockworkd.create_cloud_instances: process with pid 61486 started.
/Users/ashrith/Development/cloudwicklabs/sync/lib/clockwork/create_cloud_instances.rb:8:in `require_relative': cannot load such file -- /Users/ashrith/Development/cloudwicklabs/sync/lib/dj/create_cloud_servers (LoadError)
	from /Users/ashrith/Development/cloudwicklabs/sync/lib/clockwork/create_cloud_instances.rb:8:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `require'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `block in <top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:84:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `load'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `<main>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `<main>'
clockworkd.create_cloud_instances: process with pid 61678 started.
Starting clock for 1 events: [ Trigerring cloud instance monitor ]
Triggering 'Trigerring cloud instance monitor'
#<NameError: undefined local variable or method `perform' for Clockwork:Module>
clockworkd.create_cloud_instances: process with pid 61760 started.
Starting clock for 1 events: [ Trigerring cloud instance monitor ]
Triggering 'Trigerring cloud instance monitor'
#<NameError: undefined local variable or method `perform' for Clockwork:Module>
