clockworkd.clock: process with pid 56016 started.
I, [2014-10-02T16:26:24.245419 #56016]  INFO -- : Starting clock for 1 events: [ Trigerring cloud instance monitor ]
I, [2014-10-02T16:26:24.245645 #56016]  INFO -- : Triggering 'Trigerring cloud instance monitor'
Initializing cloud instance creator
I, [2014-10-02T16:27:24.300495 #56016]  INFO -- : Triggering 'Trigerring cloud instance monitor'
Initializing cloud instance creator
clockworkd.clock: process with pid 58104 started.
/Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/logger.rb:601:in `initialize': No such file or directory - /Users/ashrith/Development/cloudwicklabs/sync/lib/log/app.log (Errno::ENOENT)
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/logger.rb:601:in `open'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/logger.rb:601:in `create_logfile'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/logger.rb:596:in `open_logfile'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/logger.rb:551:in `initialize'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/logger.rb:318:in `new'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/logger.rb:318:in `initialize'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/activesupport-3.2.17/lib/active_support/core_ext/logger.rb:72:in `initialize'
	from /Users/ashrith/Development/cloudwicklabs/sync/lib/clock.rb:15:in `new'
	from /Users/ashrith/Development/cloudwicklabs/sync/lib/clock.rb:15:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `require'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `block in <top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:84:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `load'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `<main>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `<main>'
clockworkd.clock: process with pid 58303 started.
/Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config/environment.rb:40:in `initialize': No such file or directory - config/mongoid.yml (Errno::ENOENT)
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config/environment.rb:40:in `new'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config/environment.rb:40:in `load_yaml'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config.rb:89:in `load!'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid.rb:163:in `load!'
	from /Users/ashrith/Development/cloudwicklabs/sync/lib/clock.rb:14:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `require'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `block in <top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:84:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `load'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `<main>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `<main>'
clockworkd.clock: process with pid 58371 started.
/Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config/environment.rb:40:in `initialize': No such file or directory - ../config/mongoid.yml (Errno::ENOENT)
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config/environment.rb:40:in `new'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config/environment.rb:40:in `load_yaml'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config.rb:89:in `load!'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid.rb:163:in `load!'
	from /Users/ashrith/Development/cloudwicklabs/sync/lib/clock.rb:14:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `require'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `block in <top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:84:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `load'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `<main>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `<main>'
clockworkd.clock: process with pid 58570 started.
/Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config/environment.rb:40:in `initialize': No such file or directory - /config/mongoid.yml (Errno::ENOENT)
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config/environment.rb:40:in `new'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config/environment.rb:40:in `load_yaml'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid/config.rb:89:in `load!'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/mongoid-3.1.6/lib/mongoid.rb:163:in `load!'
	from /Users/ashrith/Development/cloudwicklabs/sync/lib/clock.rb:14:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `require'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `block in <top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:84:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `load'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `<main>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `<main>'
clockworkd.clock: process with pid 58675 started.
/Users/ashrith/Development/cloudwicklabs/sync/lib/clock.rb:16:in `<top (required)>': uninitialized constant Settings (NameError)
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `require'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `block in <top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:84:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `load'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `<main>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `<main>'
clockworkd.clock: process with pid 58764 started.
/Users/ashrith/Development/cloudwicklabs/sync/lib/clock.rb:6:in `require_relative': cannot load such file -- /Users/ashrith/Development/cloudwicklabs/sync/lib/lib/settings (LoadError)
	from /Users/ashrith/Development/cloudwicklabs/sync/lib/clock.rb:6:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `require'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:88:in `block in <top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:255:in `block in start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/daemonize.rb:82:in `call_as_daemon'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:259:in `start_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/application.rb:296:in `start'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/controller.rb:70:in `run'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:197:in `block in run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `call'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons/cmdline.rb:109:in `catch_exceptions'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/daemons-1.1.9/lib/daemons.rb:196:in `run_proc'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/gems/clockwork-1.0.0/bin/clockworkd:84:in `<top (required)>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `load'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/bin/clockworkd:23:in `<main>'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/ashrith/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/gems/2.0.0/bin/ruby_executable_hooks:15:in `<main>'
clockworkd.clock: process with pid 58805 started.
Starting clock for 1 events: [ Trigerring cloud instance monitor ]
Triggering 'Trigerring cloud instance monitor'
Triggering 'Trigerring cloud instance monitor'
Triggering 'Trigerring cloud instance monitor'
Triggering 'Trigerring cloud instance monitor'
clockworkd.clock: process with pid 59521 started.
Starting clock for 1 events: [ Trigerring cloud instance monitor ]
Triggering 'Trigerring cloud instance monitor'
Triggering 'Trigerring cloud instance monitor'
Triggering 'Trigerring cloud instance monitor'
clockworkd.clock: process with pid 60238 started.
Starting clock for 1 events: [ Trigerring cloud instance monitor ]
Triggering 'Trigerring cloud instance monitor'
#<NameError: uninitialized constant Clockwork::Delayed>
clockworkd.clock: process with pid 60902 started.
Starting clock for 1 events: [ Trigerring cloud instance monitor ]
Triggering 'Trigerring cloud instance monitor'
Triggering 'Trigerring cloud instance monitor'
Triggering 'Trigerring cloud instance monitor'
Triggering 'Trigerring cloud instance monitor'
